import pandas as pd

df_ddd = pd.DataFrame(columns=["Prefixo", "Estado", "Principais cidades(capitais em negrito)"],
                      data=[
                        ["11", "São Paulo", "São Paulo/Guarulhos/São Bernardo do Campo/Santo André/Osasco/Jundiaí"],
                        ["12", "São Paulo", "São José dos Campos/Taubaté/Jacareí/Guaratinguetá"],
                        ["13", "São Paulo", "Santos/São Vicente/Praia Grande/Cubatão/Itanhaém/Peruíbe/Registro"],
                        ["14", "São Paulo", "Bauru/Jaú/Marília/Lençóis Paulista/Lins/Botucatu/Ourinhos/Avaré"],
                        ["15", "São Paulo", "Sorocaba/Itapetininga/Itapeva"],
                        ["16", "São Paulo", "Ribeirão Preto/Franca/Araraquara"],
                        ["17", "São Paulo", "São José do Rio Preto/Barretos/Fernandópolis"],
                        ["18", "São Paulo", "Presidente Prudente/Araçatuba/Birigui/Assis"],
                        ["19", "São Paulo", "Campinas/Piracicaba/Limeira/Americana/Sumaré"],
                        ["21", "Rio de Janeiro", "Rio de Janeiro/Niterói/São Gonçalo/Duque de Caxias/Nova Iguaçu"],
                        ["22", "Rio de Janeiro", "Campos dos Goytacazes/Macaé/Cabo Frio/Nova Friburgo"],
                        ["24", "Rio de Janeiro", "Volta Redonda/Barra Mansa/Petrópolis"],
                        ["27", "Espírito Santo", "Vitória/Serra/Vila Velha/Linhares"],
                        ["28", "Espírito Santo", "Cachoeiro de Itapemirim"],
                        ["31", "Minas Gerais", "Belo Horizonte/Contagem/Betim"],
                        ["32", "Minas Gerais", "Juiz de Fora/Barbacena"],
                        ["33", "Minas Gerais", "Governador Valadares/Teófilo Otoni/Caratinga/Manhuaçu"],
                        ["34", "Minas Gerais", "Uberlândia/Uberaba/Araguari/Araxá"],
                        ["35", "Minas Gerais", "Passos/Poços de Caldas/Pouso Alegre/Varginha/Itajubá"],
                        ["37", "Minas Gerais", "Divinópolis/Itaúna/Formiga/Capitólio"],
                        ["38", "Minas Gerais", "Montes Claros/Serro/Januária"],
                        ["41", "Paraná", "Curitiba/São José dos Pinhais/Paranaguá"],
                        ["42", "Paraná", "Ponta Grossa/Castro/União da Vitória"],
                        ["43", "Paraná", "Londrina/Arapongas/Assaí/Jacarezinho/Jandaia do Sul"],
                        ["44", "Paraná", "Maringá/Campo Mourão/Astorga"],
                        ["45", "Paraná", "Cascavel/Toledo/Medianeira"],
                        ["46", "Paraná", "Francisco Beltrão/Pato Branco/Palmas/Pinhão"],
                        ["47", "Santa Catarina", "Joinville/Blumenau/Balneário Camboriú"],
                        ["48", "Santa Catarina", "Florianópolis/São José/Criciúma"],
                        ["49", "Santa Catarina", "Chapecó/Lages/Concórdia"],
                        ["51", "Rio Grande do Sul", "Porto Alegre/Canoas/Esteio/Torres"],
                        ["53", "Rio Grande do Sul", "Pelotas/Rio Grande/Bagé/Aceguá/Chuí"],
                        ["54", "Rio Grande do Sul", "Caxias do Sul/Vacaria/Veranópolis"],
                        ["55", "Rio Grande do Sul", "Santa Maria/Uruguaiana/Santana do Livramento"],
                        ["61", "Distrito Federal", "Brasília"],
                        ["62", "Goiás", "Goiânia/Anápolis/Goiás/Pirenópolis"],
                        ["63", "Tocantins", "Palmas/Araguaína/Gurupi"],
                        ["64", "Goiás", "Rio Verde/Jataí/Caldas Novas/Catalão"],
                        ["65", "Mato Grosso", "Cuiabá/Várzea Grande/Cáceres"],
                        ["66", "Mato Grosso", "Rondonópolis/Sinop/Barra do Garças"],
                        ["67", "Mato Grosso do Sul", "Campo Grande/Dourados/Corumbá/Três Lagoas"],
                        ["68", "Acre", "Rio Branco/Cruzeiro do Sul"],
                        ["69", "Rondônia", "Porto Velho/Ji-Paraná/Ariquemes"],
                        ["71", "Bahia Bahia", "Salvador/Camaçari/Lauro de Freitas"],
                        ["73", "Bahia Bahia", "Itabuna/Ilhéus/Porto Seguro/Jequié"],
                        ["74", "Bahia Bahia", "Juazeiro/Xique-Xique"],
                        ["75", "Bahia Bahia", "Feira de Santana/Alagoinhas/Lençóis"],
                        ["77", "Bahia Bahia", "Vitória da Conquista/Barreiras/Correntina"],
                        ["79", "Sergipe", "Aracaju/Lagarto/Itabaiana"],
                        ["81", "Pernambuco", "Recife/Jaboatão dos Guararapes/Goiana/Gravatá/Paulista"],
                        ["82", "Alagoas", "Maceió/Arapiraca/Palmeira dos Índios/Penedo"],
                        ["83", "Paraíba", "João Pessoa/Campina Grande/Patos/Sousa/Cajazeiras"],
                        ["84", "Rio Grande do Norte", "Natal/Mossoró/Parnamirim/Caicó"],
                        ["85", "Ceará", "Fortaleza/Caucaia/Russas/Maracanaú"],
                        ["86", "Piauí", "Teresina/Parnaíba/Piripiri/Campo Maior/Barras"],
                        ["87", "Pernambuco", "Petrolina/Salgueiro/Arcoverde"],
                        ["88", "Ceará", "Juazeiro do Norte/Crato/Sobral/Itapipoca/Iguatu/Quixadá"],
                        ["89", "Piauí", "Picos/Floriano/Oeiras/São Raimundo Nonato/Corrente"],
                        ["91", "Pará", "Belém/Ananindeua/Castanhal/Abaetetuba/Bragança"],
                        ["92", "Amazonas", "Manaus/Iranduba/Parintins/Itacoatiara/Maués/Borba"],
                        ["93", "Pará", "Santarém/Altamira/Oriximiná/Itaituba/Jacareacanga"],
                        ["94", "Pará", "Marabá/Tucuruí/Parauapebas/Redenção/Santana do Araguaia"],
                        ["95", "Roraima", "Boa Vista/Rorainópolis/Caracaraí/Alto Alegre/Mucajaí"],
                        ["96", "Amapá", "Macapá/Santana/Laranjal do Jari/Oiapoque/Calçoene"],
                        ["97", "Amazonas", "Tefé/Coari/Tabatinga/Manicoré/Humaitá/Lábrea"],
                        ["98", "Maranhão", "São Luís/São José de Ribamar/Paço do Lumiar/Pinheiro/Santa Inês"],
                        ["99", "Maranhão", "Imperatriz/Caxias/Timon/Codó/Açailândia"]
                      ])